import React from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home () {
  return (
    <>
      <Head>
        <title>Home | Software de gestión turística</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <main className={styles.main}></main>
    </>
  )
}
